# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-18 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0002_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='end_Date',
            new_name='end_date',
        ),
    ]
